#line 2 "src/myAvrAsm.lexer.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 31
#define YY_END_OF_BUFFER 32
static yyconst short int yy_accept[172] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   32,   31,
       30,   16,   16,   31,   22,   31,   31,   28,   28,   31,
       21,   26,   26,   29,   16,   16,   31,   26,   26,   31,
       31,    7,    6,    7,   12,   13,   12,    0,    0,   30,
       16,    0,    0,    0,    0,    0,    4,   28,    0,    0,
        3,    0,    0,    0,   26,   26,   26,   25,   29,   17,
       16,    0,   23,   26,   26,   26,    0,    2,    5,    0,
        0,    0,    0,    0,    0,    0,    0,   27,    0,    0,
        0,   26,   26,   26,   25,    0,   26,   26,    0,   19,
        0,   18,   19,    0,    0,    0,    0,    0,   19,    0,

       18,   19,   26,   18,    0,   19,   26,   18,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   26,    0,   26,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   26,
        0,   26,    0,   20,    0,    0,   15,    0,    0,    0,
        0,   20,   20,    0,   20,    0,   14,    0,    0,    9,
        0,    0,    0,    0,    0,    8,    0,   10,    0,    1,
        0,    0,   24,    0,    0,    0,    0,    0,   11,   11,
        0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    1,    7,
        8,    9,    1,   10,    1,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   15,   16,   17,
       18,   19,    1,    1,   21,   22,   23,   24,   25,   26,
       27,   20,   28,   20,   20,   29,   30,   31,   32,   33,
       34,   35,   20,   20,   36,   37,   20,   38,   20,   20,
        1,    1,    1,    1,   20,    1,   21,   22,   23,   24,

       25,   26,   27,   20,   28,   20,   20,   29,   30,   31,
       32,   33,   34,   35,   20,   20,   36,   37,   20,   38,
       20,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[39] =
    {   0,
        1,    2,    3,    1,    1,    1,    4,    1,    1,    1,
        1,    1,    5,    5,    6,    1,    1,    1,    1,    4,
        5,    5,    5,    5,    5,    5,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4
    } ;

static yyconst short int yy_base[187] =
    {   0,
        0,   38,   75,   77,   78,   79,   80,   86,  397,   60,
       88,  398,   90,   70,   72,   76,   82,   95,   97,   99,
       92,  111,  118,  124,  398,  126,  113,  145,  164,  125,
      398,  398,  398,  384,  398,  398,  370,  369,  359,  390,
      398,  366,  122,  108,  355,  358,  398,  141,    0,  385,
      398,  137,  142,  379,  379,  140,  150,  154,  161,  398,
      398,  350,  398,  159,  167,  169,  180,  181,  398,  353,
      161,  347,  164,  358,  171,  358,  359,    0,  193,  172,
      371,  370,  190,   92,  370,  355,  178,  171,  351,  398,
      346,  398,  345,  344,  346,  346,  340,  341,  364,  203,

      363,  358,  204,  357,  336,  328,  186,  327,  332,  336,
      327,  331,  330,  330,  318,  323,  206,  203,  322,  190,
      325,  325,  324,  345,  345,  320,  321,  323,  214,  211,
      322,  200,  339,  398,  339,  337,  398,  336,  336,  312,
      334,  332,  327,  331,  259,  284,  398,  283,  251,  398,
      250,  233,  216,  219,  244,  398,  243,  398,  235,  398,
      214,  241,  398,  218,  219,  220,  216,  230,  398,  225,
      398,  255,  261,  267,  273,  276,  278,  284,  100,  290,
      296,  302,  308,  314,  320,  326
    } ;

static yyconst short int yy_def[187] =
    {   0,
      171,  171,  172,  172,  173,  173,  174,  174,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  175,
      171,  176,  176,  171,  171,  171,  171,  177,  177,  178,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  179,  175,
      171,  175,  175,  180,  176,  176,  176,  176,  171,  171,
      171,  171,  171,  177,   29,   29,  178,  178,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  179,  175,  175,
      180,  180,  176,  176,  176,  171,   66,   66,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  175,  175,

      175,  176,  176,  176,  171,   66,   66,   66,  171,  171,
      171,  171,  171,  171,  171,  171,  175,  176,  171,   66,
      171,  171,  171,  181,  171,  171,  171,  171,  175,  176,
      171,   66,  182,  171,  171,  181,  171,  183,  171,  171,
      171,  175,  176,  171,   66,  182,  171,  184,  183,  171,
      185,  171,  171,  186,  184,  171,  185,  171,  171,  171,
      171,  186,  171,  186,  171,  186,  171,  186,  171,  186,
        0,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171
    } ;

static yyconst short int yy_nxt[437] =
    {   0,
       10,   11,   12,   13,   10,   14,   10,   10,   10,   15,
       16,   17,   18,   19,   10,   20,   10,   21,   10,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   23,   22,   22,   22,   10,   24,
       25,   26,   10,   27,   10,   10,   10,   15,   16,   17,
       18,   19,   10,   20,   10,   21,   10,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   29,   28,   28,   28,   31,   31,   31,   31,
       33,   33,   36,   38,   39,   37,   34,   34,   36,   40,
       47,   37,   41,   42,   43,   38,   39,   44,   54,   38,

       39,   51,   45,   46,   78,   38,   39,   48,   48,   48,
       48,   38,   39,   38,   39,   38,   39,   54,   38,   39,
       38,   39,   52,   53,   54,   59,   60,  104,   61,   68,
       58,   58,   49,   75,   56,   57,   42,   43,   76,   51,
       44,   56,   57,   68,   51,   62,   54,   38,   39,   38,
       39,   54,   74,   48,   48,   72,   54,   55,   55,   63,
       54,   79,   59,   60,   83,   54,   85,   85,   65,   66,
       54,   55,   55,   63,   51,   80,   58,   58,   63,   55,
       55,   55,   55,   84,   68,   68,   90,   65,   66,   93,
       64,   87,   64,   64,   95,   51,   54,   91,   68,   68,

       91,   96,   88,  106,   64,   51,  108,  101,   51,   54,
       54,   64,  132,  120,  107,  102,   51,   54,   99,   64,
      163,  163,  163,   64,  145,  130,  103,  163,  129,  100,
      117,  118,  163,   64,  159,  143,  159,  160,  142,  160,
      169,  167,  168,  163,  165,  158,  156,  161,  166,  160,
      164,  160,  158,  150,  170,   30,   30,   30,   30,   30,
       30,   32,   32,   32,   32,   32,   32,   35,   35,   35,
       35,   35,   35,   50,   50,   50,   50,   50,   50,   55,
       55,   64,   64,   64,   67,  156,  147,   67,   67,   67,
       81,   81,   64,   81,   81,   81,  136,  136,  136,  136,

      136,  136,  146,  146,  146,  146,  146,  146,  149,  149,
      149,  149,  149,  149,  155,  155,  155,  155,  155,  155,
      157,  157,  157,  157,  157,  157,  162,  162,  162,  162,
      162,  162,  154,   54,   51,  153,  152,  151,  150,  137,
      148,  147,  144,  141,  140,  139,  138,  137,  135,  134,
      133,  131,  128,  127,  126,  125,  124,  123,  122,  121,
       64,   64,  119,   54,   54,   51,   51,  116,  115,  114,
      113,  112,  111,  110,  109,  105,   54,   82,   82,   98,
       97,   94,   92,   89,   86,   54,   82,   51,   76,   77,
       73,   40,   72,   71,   70,   69,  171,    9,  171,  171,

      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171
    } ;

static yyconst short int yy_chk[437] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    3,    3,    4,    4,
        5,    6,    7,   10,   10,    7,    5,    6,    8,   11,
       17,    8,   13,   14,   14,   15,   15,   14,   84,   16,

       16,   20,   14,   16,  179,   17,   17,   18,   18,   19,
       19,   11,   11,   13,   13,   21,   21,   22,   18,   18,
       19,   19,   20,   20,   23,   24,   24,   84,   26,   30,
       23,   23,   18,   44,   22,   22,   27,   27,   44,   52,
       27,   23,   23,   30,   53,   27,   56,   24,   24,   26,
       26,   28,   43,   48,   48,   43,   57,   28,   28,   28,
       58,   52,   59,   59,   56,   64,   58,   58,   28,   28,
       29,   64,   64,   64,   80,   53,   29,   29,   29,   65,
       65,   66,   66,   57,   67,   68,   71,   29,   29,   73,
       65,   65,   66,   66,   75,   79,   83,   71,   67,   68,

       73,   75,   66,   87,   88,  100,   88,   80,  117,  118,
      103,   87,  120,  107,   87,   83,  129,  130,   79,  107,
      164,  154,  166,  120,  132,  118,   83,  170,  117,   79,
      100,  103,  168,  132,  152,  130,  159,  152,  129,  159,
      167,  165,  166,  162,  161,  157,  155,  153,  164,  152,
      154,  159,  151,  149,  168,  172,  172,  172,  172,  172,
      172,  173,  173,  173,  173,  173,  173,  174,  174,  174,
      174,  174,  174,  175,  175,  175,  175,  175,  175,  176,
      176,  177,  177,  177,  178,  148,  146,  178,  178,  178,
      180,  180,  145,  180,  180,  180,  181,  181,  181,  181,

      181,  181,  182,  182,  182,  182,  182,  182,  183,  183,
      183,  183,  183,  183,  184,  184,  184,  184,  184,  184,
      185,  185,  185,  185,  185,  185,  186,  186,  186,  186,
      186,  186,  144,  143,  142,  141,  140,  139,  138,  136,
      135,  133,  131,  128,  127,  126,  125,  124,  123,  122,
      121,  119,  116,  115,  114,  113,  112,  111,  110,  109,
      108,  106,  105,  104,  102,  101,   99,   98,   97,   96,
       95,   94,   93,   91,   89,   86,   85,   82,   81,   77,
       76,   74,   72,   70,   62,   55,   54,   50,   46,   45,
       42,   40,   39,   38,   37,   34,    9,  171,  171,  171,

      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171,  171,  171,  171,  171,
      171,  171,  171,  171,  171,  171
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/myAvrAsm.l"
#define INITIAL 0
#line 2 "src/myAvrAsm.l"
#pragma warning(disable: 4065)
#pragma warning(disable: 4083)
#pragma warning(disable: 4996)
#pragma warning(disable: 4273)


#include "InputFileRecord.h"
#include "instructions/index.h"

#include <iostream>
#include <cstring>
#include <cctype>

#include <string>
#include <map>
#include <vector>
#include <set>

using namespace std;

#include "myAvrAsm.parser.h"

#define YY_DECL extern int yylex()






/*****************************************
                GLOBALS
*****************************************/
extern InputFileRecord *__fileStack;

/**
 * Set containing all defined elements (preprocessor
 * #DEFINE statement)
 */
extern std::map<std::string, std::vector<std::string> > __defines;



/*****************************************
*               YY_BUFFER STACK
*
* include files support requires lex to 
* have separate buffers for every file read
* at the same time
******************************************/
#define MAX_INCLUDE_DEPTH 20

YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];

int include_stack_ptr = 0;



/*******************************************
                LOCAL GLOBALS
*******************************************/
std::set<std::string> _pragmaOnceDefines;

char *parseDefines(char *src);

#define incl 1

#define multilineComment 2

#define preprocessorIgnore 3

#line 591 "src/myAvrAsm.lexer.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 77 "src/myAvrAsm.l"




    
#line 751 "src/myAvrAsm.lexer.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 172 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 398 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 82 "src/myAvrAsm.l"
{
                            // This rule currently conflicts with LINE rule, which has preceedence
                            // because of the longest match rule.
                            // This is currently avoided by scanning LINE's yytext variable for 
                            // 'include' string, and REJECTing LINE rule if 'include' is found.
                            // That is a bad solution and should be avoided.
                            //
                            // TODO: This rule and the next one should be merged 
                            BEGIN(incl);
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 94 "src/myAvrAsm.l"
{ 
                        
                    /*  
                     *  Captures .include "file" statement. Opens included file and starts to 
                     *  read from it. 
                     */
                        /* got the include file name + final character " */
                        __fileStack->lineNum++;
                        yytext[yyleng-1] = '\0';
                        InputFileRecord *newFile = new InputFileRecord;
                        newFile->fileName = strdup(yytext);
                        newFile->lineNum = 1;
                        newFile->file = fopen(newFile->fileName, "r");
                        if (!(newFile->file)){
                            std::cerr   << "[" << __fileStack->fileName 
                                        << ":" << __fileStack->lineNum 
                                        << "]: Unable to open include file " 
                                        << newFile->fileName
                                        << std::endl;
                        } else {
                            if ( include_stack_ptr >= MAX_INCLUDE_DEPTH ){
                                std::cerr << "Includes nested too deep" << std::endl;
                                exit( 1 );
                            }
                            include_stack[include_stack_ptr++] = YY_CURRENT_BUFFER;

                            newFile->previous = __fileStack;
                            __fileStack = newFile;
                            yyin = __fileStack->file;
                            
                            yy_switch_to_buffer( yy_create_buffer( yyin, YY_BUF_SIZE ) );

                            std::cout << "Reading from included file:" << __fileStack->fileName << std::endl;
                        }                       
                        BEGIN(INITIAL);
                    }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 133 "src/myAvrAsm.l"
{ 
                    /**
                     * Comments that begin with ; and span to the end of the line
                     */ 
                        __fileStack->lineNum++; 
                    }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 142 "src/myAvrAsm.l"
BEGIN(multilineComment);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 144 "src/myAvrAsm.l"
BEGIN(INITIAL);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 146 "src/myAvrAsm.l"
{ 
                    /**
                    * Newline. Increases line count
                    */
                        __fileStack->lineNum++; 
                    }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 153 "src/myAvrAsm.l"
;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 159 "src/myAvrAsm.l"
{
                        __fileStack->lineNum++;
                        int startIndex = 8;
                        while ( isspace( yytext[startIndex] )) startIndex++;

                        int endIndex = startIndex;
                        while ( isalnum( yytext[endIndex] ) || yytext[endIndex] == '_') endIndex++;
                        
                        std::string key(yytext + startIndex, endIndex - startIndex);

                        std::vector<std::string> defineValues;

                        if ( yytext[endIndex] == '(' ) {
                            int fragmentStartIndex = endIndex;
                            int fragmentEndIndex = fragmentStartIndex;
                            while ( yytext[fragmentEndIndex++] != ')' );
                            char *variableName = new char[fragmentEndIndex - fragmentStartIndex];
                            strncpy(variableName, &(yytext[fragmentStartIndex+1]), (fragmentEndIndex-1) - (fragmentStartIndex+1));
                            variableName[(fragmentEndIndex-1) - (fragmentStartIndex+1)] = '\0';

                            char *definition = new char[yyleng - fragmentEndIndex];
                            strncpy(definition, &(yytext[fragmentEndIndex]), yyleng - fragmentEndIndex);
                            definition[yyleng - fragmentEndIndex - 1] = '\0';

                            char *unprocessedDefinition = definition;

                            while (1){
                                char *variable = strstr(unprocessedDefinition, variableName);
                                if (variable == NULL){
                                    defineValues.push_back(std::string(unprocessedDefinition));
                                    break;
                                }
                                defineValues.push_back(std::string(unprocessedDefinition, variable - unprocessedDefinition));
                                unprocessedDefinition += (variable - unprocessedDefinition) + strlen(variableName);
                            }
                            
                            for (std::vector<std::string>::const_iterator it = defineValues.begin();
                                 it != defineValues.end();
                                 ++it){
                            }
                            free(variableName);
                            free(definition);
                        } else {
                            while (endIndex <= yyleng && (yytext[endIndex] == ' ' || yytext[endIndex] == '\t'))
                                endIndex++;
                            if (endIndex <= yyleng){
                                defineValues.push_back(std::string(yytext + endIndex, yyleng - endIndex));
                            }
                        }
                        __defines[key] = defineValues;
                        
                    }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 212 "src/myAvrAsm.l"
{
                        __fileStack->lineNum++;
                        int startIndex = 7;
                        while ( isspace( yytext[startIndex] )) startIndex++;

                        int endIndex = startIndex;
                        while ( isalnum( yytext[endIndex] ) || yytext[endIndex] == '_') endIndex++;
                        
                        std::string key(yytext + startIndex, endIndex - startIndex);

                        if (__defines.find(key) == __defines.end()){
                            BEGIN(preprocessorIgnore);
                        }
                    }   
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 227 "src/myAvrAsm.l"
{
                        __fileStack->lineNum++;
                        int startIndex = 8;
                        while ( isspace( yytext[startIndex] )) startIndex++;

                        int endIndex = startIndex;
                        while ( isalnum( yytext[endIndex] ) || yytext[endIndex] == '_') endIndex++;
                        
                        std::string key(yytext + startIndex, endIndex - startIndex);

                        if (__defines.find(key) != __defines.end()){
                            BEGIN(preprocessorIgnore);
                        }
                    }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 242 "src/myAvrAsm.l"
{
                        if (_pragmaOnceDefines.find(std::string(__fileStack->fileName)) != _pragmaOnceDefines.end()){
                            BEGIN(preprocessorIgnore);
                        } else {
                            _pragmaOnceDefines.insert(std::string(__fileStack->fileName));
                        }
                    }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 250 "src/myAvrAsm.l"
;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 252 "src/myAvrAsm.l"
{ __fileStack->lineNum++; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 254 "src/myAvrAsm.l"
{   
                        __fileStack->lineNum++;
                        BEGIN(INITIAL); 
                    }
	YY_BREAK
case YY_STATE_EOF(preprocessorIgnore):
#line 259 "src/myAvrAsm.l"
BEGIN(INITIAL);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 262 "src/myAvrAsm.l"
{ 
                        __fileStack->lineNum++
                        ; // TODO: unput .* characters 
                    }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 268 "src/myAvrAsm.l"
{ 
                                /**
                                * Newline. Increases line count and returns token NEWLINE
                                */
                                __fileStack->lineNum++; return NEWLINE; 
                            }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 274 "src/myAvrAsm.l"
{ 
                                /**
                                * Newline. Increases line count and returns token NEWLINE
                                */
                                __fileStack->lineNum++; return NEWLINE; 
                            }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 281 "src/myAvrAsm.l"
{
                        return EQU;
                    }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 285 "src/myAvrAsm.l"
{
                        return DEF;
                    }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 289 "src/myAvrAsm.l"
{
                        return DEVICE;
                    }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 293 "src/myAvrAsm.l"
{
                        return OP_EQUALS;
                    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 297 "src/myAvrAsm.l"
{
                        return OP_COMMA;
                    }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 301 "src/myAvrAsm.l"
{
                        Label *node = new Label;
                        node->setLabel(std::string(yytext));
                        yylval.node = node;
                        return LABEL;
                    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 308 "src/myAvrAsm.l"
{
                        __fileStack->lineNum++;
                        yytext[yyleng-1] = '\0';
                        Pragma *node = new Pragma;
                        node->setPragma(std::string(yytext+8));
                        yylval.node = node;
                        return PRAGMA;
                    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 317 "src/myAvrAsm.l"
{
                        Register *node = new Register;
                        node->setRegister(std::string(yytext));
                        yylval.node = node;
                        return REGISTER_VALUE;
                    }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 324 "src/myAvrAsm.l"
{
                        char *yytextParsed;
                        std::cout << "R: " << std::string(yytext) << std::endl;
                        if ((yytextParsed = parseDefines(yytext)) == NULL){
                            Identifier *node = new Identifier;
                            node->setIdentifier(std::string(yytext));
                            yylval.node = node;
                            return IDENTIFIER;
                        } else {
                            for (int i = strlen(yytextParsed)-1; i >= 0; i--){
                                unput((int)yytextParsed[i]);
                            }
                            std::cout << "P: " << yytextParsed << std::endl;
                            free(yytextParsed);
                        }
                    }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 341 "src/myAvrAsm.l"
{
                        int temp;
                        IntegerValue *node = new IntegerValue;
                        sscanf(yytext, "%x", &temp);
                        node->setIntegerValue(temp);
                        yylval.node = node;
                        return VALUE;
                    }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 350 "src/myAvrAsm.l"
{
                        int temp;
                        IntegerValue *node = new IntegerValue;
                        sscanf(yytext, "%d", &temp);
                        node->setIntegerValue(temp);
                        yylval.node = node;
                        return VALUE;
                    }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 359 "src/myAvrAsm.l"
{
                        return WHITESPACE;
                    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 363 "src/myAvrAsm.l"
{ /* ignore whitespace not on the beginning of the line */; }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(incl):
case YY_STATE_EOF(multilineComment):
#line 365 "src/myAvrAsm.l"
{
                    /**
                     * Reacts to the end of the file. If we are currently reading a 
                     * included file, closes it and pops the previous one from the stack.
                     * If we are reading a top level file, action stops the lexer.
                     */
                        if ( --include_stack_ptr == -1 ){
                            return END_OF_FILE;
                        } else {
                    //      std::cout << "Continuing reading " << std::endl;
                            yy_delete_buffer( YY_CURRENT_BUFFER );
                            yy_switch_to_buffer( include_stack[include_stack_ptr] );
                            __fileStack = __fileStack->previous;
                    //      std::cout << "Continuing reading " << __fileStack->fileName << std::endl;
                        }
                    }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 386 "src/myAvrAsm.l"
ECHO;
	YY_BREAK
#line 1226 "src/myAvrAsm.lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 172 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 172 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 171);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 386 "src/myAvrAsm.l"


char *parseDefines(char *src){
    std::string parsed(src);
    bool wasChanged = false;
    for (std::map<std::string, std::vector<std::string> >::const_iterator it = __defines.begin();
            it != __defines.end();
            ++it
        ) {
        std::string define = it->first;
        std::vector<std::string> values = it->second;
        size_t found = parsed.find(define);
        if (found != std::string::npos){
            size_t positionOffset = found + define.length();
            size_t argumentStartIndex = 0;
            size_t argumentEndIndex = 0;
            if (positionOffset < parsed.length() && parsed[positionOffset] == '('){
                int openBracesCount = 1;
                argumentStartIndex = positionOffset + 1;
                while (1){
                    positionOffset++;
                    if (parsed[positionOffset] == '(') {
                        openBracesCount++;
                    }
                    if (parsed[positionOffset] == ')') {
                        openBracesCount--;
                        if (openBracesCount == 0){
                            argumentEndIndex = positionOffset;
                            break;
                        }
                    }
                }
                std::string variable(parsed, argumentStartIndex, argumentEndIndex - argumentStartIndex);
                std::string temp;
                temp.append(parsed, 0, found);
                for (std::vector<std::string>::const_iterator it2 = values.begin();
                     it2 != values.end();
                     ++it2){
                    temp.append(*it2);
                    if (it2 != (--values.end())){
                        temp.append(variable);
                    }
                }
                temp.append(parsed, argumentEndIndex+1, parsed.length()-(argumentEndIndex+1));
                wasChanged = true;
                parsed = temp;
            } else {
                std::string temp;
                temp.append(parsed, 0, found);
                if (values.size() > 0) {
                    temp.append(values[0]);
                }
                if (found + define.length() < parsed.length())
                    temp.append(parsed, found + define.length(), parsed.length() - (found + define.length()) );
                wasChanged = true;
                parsed = temp;
            }
        }
    }
    if (wasChanged) {
        return strdup(parsed.c_str());
    } else { 
        return NULL;
    }
}
